name: Azure Deployment

on:
  push:
    branches:
      - master  # Change this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install  # Or yarn install if you're using Yarn

    - name: Build
      run: npm run build  # Or any other build command you might have

    - name: Deploy to Azure VM
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Copy files to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        source: "dist"  # Or the folder where your build artifacts are
        target: "/var/www/html"  # Or the directory you want to deploy to on Azure VM

    - name: Restart Node.js application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        port: 22
        script: |
          npm run start  # Or any other command to restart your Node.js application
