name: Deploy to Azure Virtual Machine

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        auth-type: servicePrincipal

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to Azure Virtual Machine
      run: |
        az vm run-command invoke \
          --resource-group 123-march  \
          --name toshika  \
          --command-id RunShellScript \
          --scripts '
            sudo apt-get update
            sudo apt-get install -y unzip
            sudo apt-get install -y npm
            git clone https://github.com/ToshikaSandal/toshika-01.git
            cd toshika-01
            npm install
            npm run build
            sudo systemctl stop my-node-app
            sudo rm -rf /var/www/my-node-app/*
            sudo mv build /var/www/my-node-app
            sudo systemctl start my-node-app
          '
      env:
        VM_USERNAME: ${{ secrets.VM_USERNAME }}
        VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
